Vagrant.configure("2") do |c|
  c.berkshelf.enabled = false if Vagrant.has_plugin?("vagrant-berkshelf")
  c.vm.box = "bento/centos-7"
  c.vm.hostname = "default-centos-7.vagrantup.com"
  c.vm.synced_folder ".", "/vagrant", disabled: true
  c.vm.synced_folder "/home/gorka/.kitchen/cache", "/tmp/omnibus/cache", create: true
  c.vm.provider :virtualbox do |p|
    p.name = "kitchen-cat-job-offer-exercise-default-centos-7-30a8b00d-acc5-4842-996d-594a9c9cf62e"
    p.customize ["modifyvm", :id, "--audio", "none"]
  end
end
